# .github/workflows/main.yml

name: Run Python Tests and Deploy Docs

# Run tests only on PRs and main branch pushes
on:
  push:
    branches: [main] # Only run on pushes to main
  pull_request:
    branches: [main] # Run on PRs targeting main

# Add permissions for the workflow
permissions:
  contents: read

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 *.py test_*.py --max-line-length=88 --ignore=E203,W503

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run tests
        run: python -m unittest discover
